### ISSUE TITLE
Output path hardcoded to a specific OS X user

### ISSUE THREAD

**Issue by gsnedders** [litherum/AhemMaker#1]
With:

```
pnin:AhemMaker gsnedders$ xcodebuild -version
Xcode 8.0
Build version 8A218a
```

`xcodebuild -project AhemMaker.xcodeproj && ./build/Release/AhemMaker` results in:

```
fatal error: file /Users/gsnedders/Documents/other-projects/AhemMaker/AhemMaker/main.swift, line 869
Illegal instruction: 4
```

I have no idea what I'm doing with Swift, though. :)

**Comment by gsnedders** [comment]
Oh, wait, I'm stupid. I looked at line 86 instead of 869, which makes the hard-coded `"/Users/litherum/tmp/output.ttf"` obvious.

**Comment by gsnedders** [comment]
So yeah, I guess the bug is really "don't hardcode that path".

**Comment by litherum** [comment]
Fixed in https://github.com/litherum/AhemMaker/commit/d06af3563537e05a7940731ed52c1fdd1bc9ec43
